baseURL = "https://rlabuy.netlify.app/"
languageCode = "en-us"
title = "R Lab Uy"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "static/favicon-32x32.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "static/favicon16.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "RLabUy"

  [params.homepage_meta_tags]
    meta_description = "A team programming R solutions"
    meta_og_title = "R Lab Uy"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "static/minimalist-map.png"
    meta_og_description = "RLabUy es un equipo de desarrolladorxs de aplicaciones y paquetes de R"
    meta_twitter_card = "summary"
    meta_twitter_site = "@RLabUy"
    meta_twitter_creator = "@RLabUy"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

